version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - PLEX_CLAIM=claim-jbB9rWsMVeh1xsrG97UB
    network_mode: host
    volumes:
      - /home/media/plex/config:/config
      - /home/media/plex/transcode:/transcode
      - /home/media/data:/data
  rtorrent:
    container_name: rtorrent
    image: enpfeff/rutorrent
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1001
      - TZ=America/Toronto
    volumes:
      - /home/media/rtorrent:/config
      - /home/media/data:/downloads
    dns: 8.8.8.8
    ports:
      - 8080:80
      - 51413:51413
      - 5000:5000
      - 6881:6881/udp
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGIG=1000
      - TZ=America/Toronto
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/media/sonarr:/config
      - /home/media/data/tv:/tv
      - /home/media/data/watch:/downloads
    ports:
      - 8989:8989
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGIG=1000
      - TZ=America/Toronto
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/media/radarr:/config
      - /home/media/data/movie:/movies
      - /home/media/data/watch:/downloads
    ports:
      - 7878:7878