version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - PLEX_CLAIM=claim-jbB9rWsMVeh1xsrG97UB
    network_mode: host
    volumes:
      - /home/media/data/plex/config:/config
      - /home/media/data/plex/transcode:/transcode
      - /home/media/data:/data
  rtorrent:
    container_name: rtorrent
    image: enpfeff/rutorrent
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1001
      - TZ=America/Toronto
    volumes:
      - /home/media/rtorrent:/config
      - /home/media/data:/downloads
    dns: 8.8.8.8
    ports:
      - 8080:80
      - 51413:51413
      - 5000:5000
      - 6881:6881/udp