version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - PLEX_CLAIM=claim-jbB9rWsMVeh1xsrG97UB
    network_mode: host
    volumes:
      - /home/media/data/plex/config:/config
      - /home/media/data/plex/transcode:/transcode
      - /home/media/data:/data
  rtorrent:
    container_name: rtorrent
    image: kfei/docktorrent
    restart: unless-stopped
    environment: 
      - UPLOAD_RATE=0
    volumes:
      - /home/media/rtorrent:/rtorrent
    dns: 8.8.8.8
    ports:
      - 8080:80
      - 45566:45566 
      - 9527:9527/udp