version: '2'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8081:80/tcp
    environment:
      - TZ=America/Toronto
      - WEBPASSWORD=Passwd12!
    volumes:
      - ./etc-pihole/:/etc/pihole/'
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - what
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - TZ=America/Toronto
      - PGID=1001
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - /home/enpfeff/config/homebridge:/homebridge
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - PLEX_CLAIM=claim-jbB9rWsMVeh1xsrG97UB
    network_mode: host
    volumes:
      - /home/enpfeff/config/plex:/config
      - /home/enpfeff/config/plex/transcode:/transcode
      - /data:/data
  rtorrent:
    container_name: rtorrent
    image: enpfeff/rutorrent
    restart: unless-stopped
    environment:
      - PGID=1001
      - PUID=1000
      - TZ=America/Toronto
    volumes:
      - /home/enpfeff/config/rtorrent:/config
      - /data:/downloads
    dns: 8.8.8.8
    ports:
      - 8080:80
      - 55950:55950
      - 5000:5000
      - 6881:6881/udp
    networks:
      - what
  web:
    container_name: web
    image: nginx
    volumes:
      - /home/enpfeff/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/enpfeff/config/nginx/htpasswd:/etc/nginx/htpasswd
      - /home/enpfeff/config/nginx:/etc/nginx/keys
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=home.enpfeff.com
      - NGINX_PORT=80
    networks:
      - what
networks:
  what: 
